name: Test

on:
  push:
    branches:
      - main
      - "release/v*.*.*"
  pull_request:
    branches: [main]

jobs:
  go-static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true
      - name: Verify go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v
          skip-cache: true

  eslint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: "web/yarn.lock"
      - run: yarn
        working-directory: web
      - name: Run eslint check
        run: yarn lint
        working-directory: web

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: "web/yarn.lock"
      - run: yarn
        working-directory: web
      - name: Run frontend build
        run: yarn build
        working-directory: web

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true
      - name: Run all tests
        run: go test -v ./... | tee test.log; exit ${PIPESTATUS[0]}
      - name: Pretty print tests running time
        run: grep --color=never -e '--- PASS:' -e '--- FAIL:' test.log | sed 's/[:()]//g' | awk '{print $2,$3,$4}' | sort -t' ' -nk3 -r | awk '{sum += $3; print $1,$2,$3,sum"s"}'
